### ISSUE TITLE
Switching token won't change Welcome Popup content

### ISSUE THREAD

**Issue by Haraguroicha** [CCIP-App/CCIP-iOS#26]
token A switch to token B will affected once when click different token url

![image](https://user-images.githubusercontent.com/1715541/63798870-6ff49a00-c93d-11e9-9887-c2b2e5516bb8.png)

**Comment by Haraguroicha** [comment]
seems fixed in 0ef102a

**Comment by TinkerTeam** [comment]
@Haraguroicha 這個真的有解你那個問題嗎？
