### ISSUE TITLE
icon from url will mismatch the size

### ISSUE THREAD

**Issue by Haraguroicha** [CCIP-App/CCIP-iOS#27]
![image](https://user-images.githubusercontent.com/1715541/63857971-3d977b00-c9d7-11e9-9bc2-17780aca272b.png)

**Comment by FrankWu100** [comment]
should be fixed by https://github.com/CCIP-App/CCIP-iOS/commit/f989f7d3011205608b2dea3fcb14997b5540c62d, please take a try.

**Comment by FrankWu100** [comment]
I think this may not be the perfect patch.
Although the image size already correct, but the image quality goes worse.
But this still can be the short term solution.

So long term, I guess should use a XIB file to fixed the UIImageView size.

**Comment by Haraguroicha** [comment]
@FrankWu100 Try to grab the UIImage data from Nuke, and put them into UITableCellView`'s `UIImageView might resolve this issue?

**Comment by Haraguroicha** [comment]
wait a minute, why you reassign this issue to me ?? are you sure this is resolved ?
if you don't sure is resolved, next time please mark a label for your short term solution, thanks.

**Comment by Haraguroicha** [comment]
currently size mismatch problem was resolved, but resolution might be a problem, or maybe original icon is lower then we need?

![image](https://user-images.githubusercontent.com/1715541/91479022-6ea0d900-e8d3-11ea-8027-7b1ee7d7fb81.png)

**Comment by Haraguroicha** [comment]
since next generation of OPass for iOS release v4 with rewrite whole project, that issues can close, please create another ticket for any further related needs.
