### ISSUE TITLE
[Refactor] Add Gemfile

### ISSUE THREAD

**Issue by jamfly** [CCIP-App/CCIP-iOS#34]
## Summary

in this project, we didn't have a specified CocoaPod version which may lead people use different environment to develop.

## Plan
1. add a guide of setup ruby environment in README
2. add Gemfile

## Advantage
1. everybody share one setting, which can decline the rate of making mistake
2. in the future [fastlane](https://github.com/fastlane/fastlane) may be needed, and we could also share the same version of it.

**Comment by Haraguroicha** [comment]
Currently, we doesn’t request developers must have CocoaPod for this project, we put all of Pods into repository for sure there are the same Pods for everyone, if someone update the Pods or add a pod, we doesn’t care the CocoaPod version, just don’t break the sources is first priority

**Comment by Haraguroicha** [comment]
since next generation of OPass for iOS release v4 with rewrite whole project, that issues can close, please create another ticket for any further related needs.
