### ISSUE TITLE
Remove existing ticket

### ISSUE THREAD

**Issue by davidhcefx** [CCIP-App/CCIP-iOS#36]
I opened up a link, which then registered a ticket to the app. However, this ticket will then be bounded to the app, and ***in no way*** can it be removed!

This is especially frustrating when one already distributed some tickets to others and then decided to buy some more tickets for his or her own. If the person happened to have some tickets registered, then there’s no way to correct it back, even if deleting the app and reinstalling it.

**Comment by Haraguroicha** [comment]
Currently have two unusual way to remove the existing ticket

1. Use an empty token Link, means no token to overwrite current token
2. Use dev mode in app by following step
    1. goto more tab
    2. tapping more than 10 times on logo
    3. switch back to fastpass tab
    4. tapping more than 10 times on display name
    5. token removed
