### ISSUE TITLE
午餐畫面顯示葷素

### ISSUE THREAD

**Issue by yoyo930021** [CCIP-App/CCIP-iOS#45]
需根據葷食或素食 顯示對應顏色

**Comment by denny0223** [comment]
https://github.com/CCIP-App/CCIP-Android/blob/0c6448a170786179dc7f94ffd88ec288ebaa3d83/app/src/main/res/values/colors.xml#L6-L7

**Comment by viere1234** [comment]
Fixed in [bd68629](https://github.com/CCIP-App/CCIP-iOS/commit/bd686295310a0dacc9e09878380ea49b21ec7278)
