### ISSUE TITLE
議程需要顯示類型

### ISSUE THREAD

**Issue by yoyo930021** [CCIP-App/CCIP-iOS#46]
https://coscup.org/2020/json/session.json
`session[].type` 與 `session_types`

**Comment by gnehs** [comment]
設計做好了

<img width="718" alt="image" src="https://user-images.githubusercontent.com/16719720/168473579-0fc8db20-b3a1-4596-9267-b20fe983e73f.png">

`signpost.right` `#FFCC00`

**Comment by viere1234** [comment]
Fixed in [bd68629](https://github.com/CCIP-App/CCIP-iOS/commit/bd686295310a0dacc9e09878380ea49b21ec7278)
