### ISSUE TITLE
與 Android 對齊主畫面功能使用的 icon

### ISSUE THREAD

**Issue by yoyo930021** [CCIP-App/CCIP-iOS#47]
iOS: https://github.com/CCIP-App/CCIP-iOS/blob/8f170f1abb80401559a6b405b421157015618ad3/OPass/Views/MainView.swift#L235

Android: https://github.com/CCIP-App/CCIP-Android/blob/dev/app/src/main/java/app/opass/ccip/ui/DrawerMenuAdapter.kt#L140

**Comment by viere1234** [comment]
Checked both with:

1. `FAST_PASS` `.fastpass`
2. `SCHEDULE` `.schedule`
3. `ANNOUNCEMENT` `.announcement`
4. `PUZZLE` `.puzzle`
5. `TICKET` `.ticket`
6. `TELEGRAM` `.telegram`
7. `IM` `.im`
8. `SPONSORS` `.sponsors`
9. `STAFFS` `.staffs`
10. `VENUE` `.venue`
11. `WIFI` `.wifi`

are identical.
