### ISSUE TITLE
快速通關顏色與樣式修正

### ISSUE THREAD

**Issue by gnehs** [CCIP-App/CCIP-iOS#48]
![](https://user-images.githubusercontent.com/16719720/168514668-9397b8da-1041-4faf-af98-ecbffacaeff9.jpg)

輸入框的邊框 `#d1d1d5`

輸入框的邊框在非 focus 時邊框的 `lineWidth` 應為 `1`

背景色應為 `#fff`

**Comment by viere1234** [comment]
Fix in [b086603](https://github.com/CCIP-App/CCIP-iOS/commit/b0866032923aeff1617b96f6fc4e5785bdea977d)
