### ISSUE TITLE
Session table not showing time in the device timezone

### ISSUE THREAD

**Issue by uranusjr** [CCIP-App/CCIP-iOS#54]
ref pycontw/pycon.tw#1148

Session table currently shows the time as returned by the API, but does not seem to convert it to the device’s current timezone. This causes the time in the session table to show in whatever timezone the API server returns (UTC for PyCon TW’s case) instead.

The Android client has a different behaviour and converts the time to the client timezone. I think the behaviour can be implemented in either way (respect the server’s timezone or the client’s timezone) since both behaviour has valid use cases, but the two platforms should match, not have different results.

**Comment by viere1234** [comment]
Fixed in 53c2161, OPass for iOS 4.2.4
