### ISSUE TITLE
use AFNetworking instead

### ISSUE THREAD

**Issue by Haraguroicha** [CCIP-App/CCIP-iOS#9]

**Comment by FrankWu100** [comment]
好喔

**Comment by FrankWu100** [comment]
完成，@Haraguroicha 確認一下，沒問題的話交給你把 submodules 移掉。

- 6453d02f41074dd3d49153a0381abbba353afa56
- 3af0cee5235f8ab3714ce0b069c957594e39f6e5
- a4232d22eb4ea3582f5a173918b94bd0d35b9606
- 3b0f7b7f130660566f24b464e63b7548e64f99fa
- f5a3511363f3e423373b494bb6f7886e074ae9f8
- a9f461c72daeb00ab75094832f0e053e4dddf6aa
- 41209fb3952a5ff5bca4f2589834d572ff7779d1
- 69a69205f9c6e82e76e0c4d81b7f3c0d3e511a58
- 4540246e7b5a207231cf9c5c8901b448a67e2961
- edb9452c1c82f78f3d73bc926bf3a913c4cd9f82
- 62649f5e921a02aaf7b750dba589d869a7ecb00a

**Comment by Haraguroicha** [comment]
okay, pending to review

**Comment by Haraguroicha** [comment]
confirmed and cleanup all useless code on 4a1bd48
